# Spring 配置
spring:
  # 数据源
  datasource:
    # 数据库驱动
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    # 数据库用户名
    username: root
    # 数据库密码
    password: root
    # 数据库连接串
    url: jdbc:p6spy:mysql://127.0.0.1:3306/api-analysis?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=UTF-8
#
# MyBatis 配置
mybatis:
  # 扫描 Mapper XML 文件
  mapper-locations: classpath:mapper/*.xml
